version: '3.8'

services:
  # Main application
  attendance-dashboard:
    build: .
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=False
      - SECRET_KEY=${SECRET_KEY}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - MANAGER_USERNAME=${MANAGER_USERNAME}
      - MANAGER_PASSWORD=${MANAGER_PASSWORD}
      - HOST=0.0.0.0
      - PORT=8000
      - SESSION_COOKIE_SECURE=false  # Disabled for HTTP testing
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - attendance-network
    labels:
      - "traefik.enable=true"
      # Domain rule (original)
      - "traefik.http.routers.attendance-domain.rule=Host(`attendance.redstoneintelligence.com`)"
      - "traefik.http.routers.attendance-domain.tls=true"
      - "traefik.http.routers.attendance-domain.tls.certresolver=letsencrypt"
      # IP-based rules for local testing
      - "traefik.http.routers.attendance-ip1.rule=Host(`10.100.1.187`)"
      - "traefik.http.routers.attendance-ip1.entrypoints=web"
      - "traefik.http.routers.attendance-ip2.rule=Host(`192.168.0.246`)"
      - "traefik.http.routers.attendance-ip2.entrypoints=web"
      - "traefik.http.routers.attendance-localhost.rule=Host(`localhost`)"
      - "traefik.http.routers.attendance-localhost.entrypoints=web"
      # Service configuration
      - "traefik.http.services.attendance.loadbalancer.server.port=8000"

  # Reverse proxy with SSL
  traefik:
    image: traefik:v3.0
    command:
      - "--api.dashboard=true"
      - "--api.debug=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.traefik.address=:8080"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=${SSL_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      # Disable HTTPS redirect for local testing
      # - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      # - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      # - "--entrypoints.web.http.redirections.entryPoint.permanent=false"
      - "--log.level=DEBUG"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    restart: unless-stopped
    networks:
      - attendance-network
    depends_on:
      - attendance-dashboard
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`localhost`) && PathPrefix(`/dashboard`)"
      - "traefik.http.routers.traefik.entrypoints=traefik"
      - "traefik.http.routers.traefik.service=api@internal"

networks:
  attendance-network:
    driver: bridge

volumes:
  postgres_data:
